### ISSUE TITLE
Errors after npm run dev

### ISSUE THREAD

**Issue by ii5mail** [greenpress/greenpress#139]
`l greenpress\apps\greenpress\node_modules\.bin\\..\..\..\..\packages\pm2-launcher\bin\dev"' is not recognized as an internal or external command,
erna ERR! npm run dev exited 1 in '@greenpress/greenpress'
lerna ERR! npm run dev exited 1 in '@greenpress/greenpress'`

**Comment by davidmeirlevy** [comment]
Hi,

Please specify:
Node version
Npm version

Did you run npm install and npm run build?

**Comment by ii5mail** [comment]
`PS D:\Projects\Fiverr\fiverr\greenpress> node -v
v17.1.0
PS D:\Projects\Fiverr\fiverr\greenpress> npm --version
8.1.2
` Yes, I did npm install and npm run build

**Comment by davidmeirlevy** [comment]
the command is running this file:
https://github.com/greenpress/greenpress/blob/main/packages/pm2-launcher/bin/dev

probably that this file needs a first-line with mentioning the terminal, or something that needs to work on windows.
this file is great for bash or zsh, but not with CMD.

**Comment by ii5mail** [comment]
i think this script is not installing pm2-launcher so ,cmd is saying this script is not recognized as internal or external command

**Comment by davidmeirlevy** [comment]
old version. closing.
