### ISSUE TITLE
[assets] [enhancement] add ability to manage cloudinary assets

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/greenpress#144]
Following the same API of the assets service, add the ability to manage assets through cloudinary.

1. add / edit storage with kind: `cloudinary`.
2. upload / remove / update / get list of assets from cloudinary API.

**Comment by davidmeirlevy** [comment]
@OmerGronich what do you say about this feature? you're already familiar with this area..

**Comment by OmerGronich** [comment]
> @OmerGronich what do you say about this feature? you're already familiar with this area..

I would love to take this feature :) 
I'll start working on it this week

**Comment by davidmeirlevy** [comment]
@OmerGronich you're assigned :)

**Comment by OmerGronich** [comment]
@davidmeirlevy 

A few questions - 

1. The maximum page size for a single request is 500 and the minimum is 10 in cloudinary. What is the expected response from `get list of assets`, do you want the full list, the minimum or 500? some number in the middle? let me know

2. The loadFiles method is expected to return an object in a specific shape, with a property called `updated` however Cloudinary does not provide updated_at field for their assets, only created_at. Do you want me to skip this property?
