### ISSUE TITLE
[docs] remove current docs folder and create a new vitepress project

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/greenpress#171]
The current `docs` folder contains documentation for the old version of greenpress.
the platform was changed a lot since then, and also it's now better to create documentation websites using vitepress instead of vuepress.

so this issue is about making a fresh start!

1. remove the current docs folder.
2. create the new vitepress project following those commands:

run:
```sh
mkdir docs && cd docs
npm init -y
npm i -D vitepress vue
mkdir echo '# Hello GreenPress' > docs/index.md
```

add those lines to `docs/package.json`:
```json
  "scripts": {
    "dev": "vitepress dev docs",
    "build": "vitepress build docs",
    "serve": "vitepress serve docs"
  },
```

now run the docs in order to test it:

```sh
npm run dev
```

if both dev and build scripts work - this issue will be good to go!

**Comment by Niravprajapati1** [comment]
i am getting this error "lerna ERR! EFILTER  No packages  remain after  filtering [ '
![Screenshot_2022-09-25-11-50-57-41](https://user-images.githubusercontent.com/83688779/192131051-7759e4e8-cab2-499a-b588-1122fe19657e.jpg)
greenpress/greenpress']  how can i solve can you help me ?

**Comment by davidmeirlevy** [comment]
Yep. This folder was deleted recently.
If there are still references to it, they should be removed.

**Comment by davidmeirlevy** [comment]
@Niravprajapati1 what is the command you're running?

**Comment by Niravprajapati1** [comment]
> @Niravprajapati1 what is the command you're running?

npm start
