### ISSUE TITLE
[blog-front] Hot module replacement  (HMR) doesn't work on windows machine

### ISSUE THREAD

**Issue by or-yam** [greenpress/greenpress#46]
While runnig a project in dev mode with blog-front as local  service on windows machine the HMR dosn't work. 

To work around it, in the local blog-front service add to `nuxt.config.js` file: 
```javascript
 watchers: {
    webpack: {
      poll: true
    }
  },
  ```

**Comment by davidmeirlevy** [comment]
old version. not relevant.
