### ISSUE TITLE
[blog-front] [Enhancement] When using external themes, display favicon correctly

### ISSUE THREAD

**Issue by drorrose** [greenpress/greenpress#48]
1. Create a new blog using the CLI. (`greenpress create my-app`).
2. Create a new theme using the CLI. (`greenpress theme my-theme `).
3. in this theme folder, add a folder named `_assets` and put a `favicon.ico` file.

**expected result:**
1. the icon will be shown in the app.
2. the icon will be available at `localhost:3000/_assets/favicon.ico`
3. every file on this `_assets` folder should be also available.

**steps to the solution:**
1. on `helpers/set-theme.js` should check if the theme has a `_assets` folder, and if true -> make another link from `static/_assets` to this `_assets` folder.
2. in `nuxt.config.js:20` there's a link to the default `favicon.ico`. if `static/_assets/favicon.ico` exists -> replace this path to the theme's favicon.

**Comment by davidmeirlevy** [comment]
old version. not relevant.
