### ISSUE TITLE
[docs] Setup Links and Spelling

### ISSUE THREAD

**Issue by Made-of-Clay** [greenpress/greenpress#87]
Apologies for only just now getting around to this. Your docs (which are a good read) have a number of GitHub links to [theme components that are 404s](https://docs.greenpress.info/guide/customize.html#setps). Also, you'll notice that the section heading is spelled "Setps" instead of "Setups". Things are looking quite promising otherwise! :)

([I commented on your Reddit Vue post in /r/vuejs](https://www.reddit.com/r/vuejs/comments/nlq5xl/greenpress_a_wordpressalternative_written_from/))

**Comment by davidmeirlevy** [comment]
Hi 👋 

thanks for this issue.
Would you like to also contribute the changes?
