### ISSUE TITLE
Change all master branches to be "main" instead of "master"

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/greenpress#9]
It should affect:
1. pipelines.
2. pipelines' hooks config.
3. `greenpress-pm2` git sub-modules.
4. clone local dev repositories using the `greenpress-cli`.
5. `.env.example` file for scaled composition.

**Comment by davidmeirlevy** [comment]
Thanks for the ambition, but we need that one from the DevOps team will take it because they need to change the pipeline build triggers in the CI/CD system.
If you want, there are many other issues in this organization! this platform has several micro-services: 2 frontends, 2 for cli and terminal tools, and the rest as backend.

Choose the one you like and go for it :)
We will be happy to assist and guide you on the way to contribute!

**Comment by android-lewis** [comment]
Hi David, I sort of realised after a few minutes that it probably was not one I could take 😆 . I'll keep an eye out thanks!
