### ISSUE TITLE
[CLI] greenpress create app using node v14 seem to be broken 

### ISSUE THREAD

**Issue by LironHazan** [greenpress/greenpress#92]
Couldn't create the app using node version 14 

C02Y504VJHD3:dev-liron lironh$ greenpress create app
/Users/lironh/.nvm/versions/node/v15.12.0/lib/node_modules/@greenpress/cli/controllers/create.js:17
	if (!(await execute(`git clone https://github.com/greenpress/greenpress ${name}`, 
	^
ReferenceError: execute is not defined

**Comment by davidmeirlevy** [comment]
fixed.
