### ISSUE TITLE
[CLI] greenpress start gets stuck on 12% progress, although it finishes running 

### ISSUE THREAD

**Issue by ranwahle** [greenpress/greenpress#94]
Steps to reproduce

1. Go to greenpress app directory
2. Run greenpress start <args> (the scenario happens without args as well)
3. Watch the progress

Expected result: The progress should reach 100%.
Actual result: The progress is stuck at 12% although all docker containers are up and running.

**Comment by davidmeirlevy** [comment]
CLI was refactored. will not happen.
